---
# tasks file for R

- name: 0. Verificar R
  yum:
    list: R
  register: R_result
- debug: 
    var: R_result

- name: 1. Instalar R.
  yum:
    name: R
    state: present
 #   register: result
 # until: 'result.rc == 0'
  retries: 5
  delay: 10
  #when: R_result["results"]["yumstate"] == "available"

